name: Android CI Build

on: [push] # Trigger build on pushes to the repo

jobs:
  build:
    runs-on: ubuntu-latest # Use a Linux runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17 # Or JDK 17 if the project needs it
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt' # Or another distribution
        java-version: '17' # Match project requirement

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew # gradlew is the gradle wrapper script

    - name: Build with Gradle
      run: ./gradlew clean assembleDebug -Porg.gradle.jvmargs="-Xmx4g -XX:+HeapDumpOnOutOfMemoryError"
   
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk # Name of the artifact
        path: app/build/outputs/apk/debug/app-debug.apk # Path to the built APK (might vary slightly!)
